// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "activity" section.

import React from 'react';
import FeaturesBento from '@/components/sections/features/FeaturesBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ActivitySection(): React.JSX.Element {
  return (
    <div id="activity" data-section="activity">
        <SectionErrorBoundary name="activity">
              <FeaturesBento
          tag="SHOP BY ACTIVITY"
          title="Diverse Motion"
          description="为每种身心频率设计的专属穿搭。"
          features={[
            {
              title: "Pilates",          description: "核心控制的平衡美学。",          bentoComponent: "media-stack",          mediaItems: [
                { imageSrc: "http://img.b2bpic.net/free-photo/side-view-woman-looking-mirror_23-2149832697.jpg" },
                { imageSrc: "http://img.b2bpic.net/free-photo/side-view-women-doing-pilates-together_23-2150830109.jpg" },
                { imageSrc: "http://img.b2bpic.net/free-photo/young-brunette-female-standing-having-break-smiling_7502-9765.jpg" },
              ]
            },
            {
              title: "Yoga",          description: "呼吸与伸展的轻盈感。",          bentoComponent: "media-stack",          mediaItems: [
                { imageSrc: "http://img.b2bpic.net/free-photo/young-beautiful-contemporary-dancer-posing-white-wall-copy-space_176420-7239.jpg" },
                { imageSrc: "http://img.b2bpic.net/free-photo/woman-meditating-with-tray-with-candles_23-2148896059.jpg" },
                { imageSrc: "http://img.b2bpic.net/free-photo/rolled-exercise-mat-bottle-water-parquet-floor_637285-5746.jpg" },
              ]
            },
            {
              title: "Everyday",          description: "跨越场景的时尚穿搭。",          bentoComponent: "media-stack",          mediaItems: [
                { imageSrc: "http://img.b2bpic.net/free-photo/fit-woman-with-water-bottle-leaning-column-gym_23-2147949477.jpg" },
                { imageSrc: "http://img.b2bpic.net/free-photo/woman-applying-face-serum-her-beauty-routine_23-2150166415.jpg" },
                { imageSrc: "http://img.b2bpic.net/free-photo/young-adult-tokyo-streets_23-2149389172.jpg" },
              ]
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
