// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "best-sellers" section.

import React from 'react';
import PricingMediaCards from '@/components/sections/pricing/PricingMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function BestSellersSection(): React.JSX.Element {
  return (
    <div id="best-sellers" data-section="best-sellers">
        <SectionErrorBoundary name="best-sellers">
              <PricingMediaCards
        tag="BEST SELLERS"
        title="Brand Favorites"
        description="都市女性最愛的熱銷常態單品。"
        plans={[{"features":["四向高彈面料","高腰包覆剪裁","透氣吸濕排汗"],"imageSrc":"https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786489246002-ux7540he.png","tag":"熱銷首選","price":"NT$ 990","primaryButton":{"href":"#","text":"選購商品"},"period":" / 件"},{"period":" / 套","imageSrc":"https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786489246003-djlqkdun.png","tag":"經典套裝","features":["零觸感親膚貼合","極簡休閒剪裁","百搭質感色系"],"price":"NT$ 1,290","primaryButton":{"href":"#","text":"選購商品"}},{"tag":"新品推薦","price":"NT$ 790","imageSrc":"https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786489246003-phlk3b6d.png","features":["輕量無感支撐","高透氣親膚面料","永續環保材質"],"period":" / 件","primaryButton":{"text":"選購商品","href":"#"}}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
