// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "best-sellers" section.

import React from 'react';
import PricingMediaCards from '@/components/sections/pricing/PricingMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function BestSellersSection(): React.JSX.Element {
  return (
    <div id="best-sellers" data-section="best-sellers">
        <SectionErrorBoundary name="best-sellers">
              <PricingMediaCards
          tag="BEST SELLERS"
          title="Brand Favorites"
          description="都市女性最爱的常态化单品。"
          plans={[
            {
              tag: "Top Rated",          price: "NT$ 990",          period: "单品",          features: ["四向弹性面料", "高腰收腹剪裁", "速干吸湿"],
              primaryButton: { text: "VIEW PRODUCT", href: "#" },
              imageSrc: "http://img.b2bpic.net/free-photo/bed-linen-background-home-decor_53876-133367.jpg"
            },
            {
              tag: "Essentials",          price: "NT$ 1,290",          period: "套装",          features: ["极简设计", "零触感贴合", "城市百搭色"],
              primaryButton: { text: "VIEW PRODUCT", href: "#" },
              imageSrc: "http://img.b2bpic.net/free-photo/workout-clothes-sports-ba-running_1303-1763.jpg"
            },
            {
              tag: "New In",          price: "NT$ 790",          period: "单品",          features: ["轻盈透气", "支撑性强", "环保面料"],
              primaryButton: { text: "VIEW PRODUCT", href: "#" },
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-composition-sport-elements_23-2149006303.jpg"
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
