// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "complete-look" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CompleteLookSection(): React.JSX.Element {
  return (
    <div id="complete-look" data-section="complete-look">
        <SectionErrorBoundary name="complete-look">
              <MetricsMediaCards
          tag="COMPLETE THE LOOK"
          title="Build Your Style"
          description="Mix & Match 你的都市运动穿搭。"
          metrics={[
            { value: "100+", title: "组合方式", description: "自由搭配你的运动与日常衣橱。", imageSrc: "http://img.b2bpic.net/free-photo/portrait-fit-athlete-outdoor_23-2148381893.jpg" },
            { value: "15", title: "设计细节", description: "每一个缝线都为都市美学服务。", imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-transgender-wearing-sunglasses_23-2149105415.jpg" },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
