// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="STAY CONNECTED"
          text="订阅品牌通讯，获取最新都市风格灵感与优先购买权。"
          primaryButton={{ text: "JOIN NOW", href: "#" }}
          secondaryButton={{ text: "FOLLOW US", href: "#" }}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
