// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "editorial" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function EditorialSection(): React.JSX.Element {
  return (
    <div id="editorial" data-section="editorial">
        <SectionErrorBoundary name="editorial">
              <TestimonialMarqueeCards
          tag="LIFESTYLE"
          title="City Editorial"
          description="不仅是运动，更是你的都市日常态度。"
          testimonials={[
            { name: "Coffee Session", role: "Cafe Mood", quote: "从健身房到咖啡厅， effortlessly.", imageSrc: "http://img.b2bpic.net/free-photo/young-woman-drinking-coffee-talking-phone-cafe_1303-27372.jpg" },
            { name: "Modern Living", role: "Apartment", quote: "居家运动也是一种仪式感。", imageSrc: "http://img.b2bpic.net/free-photo/crop-woman-sitting-book-chocolate_23-2147888585.jpg" },
            { name: "Street Chic", role: "City Street", quote: "穿出自信的都市节奏。", imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-serious-curly-haired-woman-dressed-brown-sportswear-carries-rolled-karemat-goes-sport-regularly-looks-away-poses-against-modern-building-city-healthy-lifestyle-concept_273609-60545.jpg" },
            { name: "Weekend Vibe", role: "Studio", quote: "周末 Pilates 的完美陪伴。", imageSrc: "http://img.b2bpic.net/free-photo/portrait-fitness-girl-doing-yoga-rubber-mat-home-workout-indoors-kitchen-wearing_1258-200209.jpg" },
            { name: "Urban Flow", role: "Studio", quote: "专注当下的自我对话。", imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-couple-decorating-home_23-2150633264.jpg" },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
