/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const testimonials = [
  {
    name: "Coffee Session",
    role: "Cafe Mood",
    quote: "从健身房到咖啡厅， effortlessly.",
    imageSrc: "http://img.b2bpic.net/free-photo/young-woman-drinking-coffee-talking-phone-cafe_1303-27372.jpg"
  },
  {
    name: "Modern Living",
    role: "Apartment",
    quote: "居家运动也是一种仪式感。",
    imageSrc: "http://img.b2bpic.net/free-photo/crop-woman-sitting-book-chocolate_23-2147888585.jpg"
  },
  {
    name: "Street Chic",
    role: "City Street",
    quote: "穿出自信的都市节奏。",
    imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-serious-curly-haired-woman-dressed-brown-sportswear-carries-rolled-karemat-goes-sport-regularly-looks-away-poses-against-modern-building-city-healthy-lifestyle-concept_273609-60545.jpg"
  },
  {
    name: "Weekend Vibe",
    role: "Studio",
    quote: "周末 Pilates 的完美陪伴。",
    imageSrc: "http://img.b2bpic.net/free-photo/portrait-fitness-girl-doing-yoga-rubber-mat-home-workout-indoors-kitchen-wearing_1258-200209.jpg"
  },
  {
    name: "Urban Flow",
    role: "Studio",
    quote: "专注当下的自我对话。",
    imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-couple-decorating-home_23-2150633264.jpg"
  }
];

type Testimonial = {
  name: string;
  role: string;
  quote: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const EditorialInline = () => {
  return (
    <section aria-label="Editorial section" className="py-16 md:py-24">
      <div className="flex flex-col gap-10 md:gap-14 w-content-width mx-auto">
        {/* Header */}
        <div className="flex flex-col items-center gap-3 text-center">
          <div className="px-3 py-1 text-xs tracking-wider font-medium uppercase card rounded w-fit text-accent">
            EDITORIAL & LIFESTYLE
          </div>

          <TextAnimation
            text={"身心好处 × 极致舒适"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-5xl md:text-6xl 2xl:text-7xl font-semibold text-center text-balance leading-[1.15]"
          />

          <TextAnimation
            text={"一半探索运动赋予身心的澎湃能量，一半体会服饰带来的云感无感包覆。"}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-base md:text-lg text-accent text-center text-balance"
          />
        </div>

        {/* Dual Split Cards */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 md:gap-10">
          {/* Part 1: Benefits of Movement */}
          <div className="card p-7 md:p-9 rounded-2xl flex flex-col justify-between gap-6 border border-accent/15">
            <div className="flex flex-col gap-5">
              <div className="flex items-center justify-between border-b border-accent/15 pb-3.5">
                <span className="text-xs font-semibold tracking-widest text-accent uppercase">Part 01</span>
                <span className="text-xs font-medium px-2.5 py-1 bg-accent/10 rounded-full text-foreground">MOVEMENT & WELLNESS</span>
              </div>

              <div>
                <h3 className="text-2xl md:text-3xl font-bold text-foreground mb-2">
                  运动带来的身心益处
                </h3>
                <p className="text-sm text-accent leading-relaxed">
                  规律的练习不仅是形体的雕琢，更是专注当下的自我沉淀，让身体重获轻盈与活力。
                </p>
              </div>

              <div className="relative h-60 md:h-64 rounded-xl overflow-hidden my-1">
                <img
                  src="https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786484971918-jre4hmkb.jpg"
                  alt="Movement & Wellness"
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent flex items-end p-4">
                  <p className="text-white text-xs md:text-sm font-medium">释放内啡肽，提升日常专注力与充沛精神</p>
                </div>
              </div>

              <ul className="space-y-3.5 pt-1">
                <li className="flex items-start gap-3">
                  <div className="size-5 rounded-full bg-foreground/10 text-foreground flex items-center justify-center shrink-0 mt-0.5 text-xs font-bold">1</div>
                  <div>
                    <h4 className="text-sm font-semibold text-foreground">释放压力与焦虑</h4>
                    <p className="text-xs text-accent mt-0.5">在呼吸与动作间放空大脑，促进快乐激素分泌，获得内心的平静。</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <div className="size-5 rounded-full bg-foreground/10 text-foreground flex items-center justify-center shrink-0 mt-0.5 text-xs font-bold">2</div>
                  <div>
                    <h4 className="text-sm font-semibold text-foreground">改善体态与久坐僵硬</h4>
                    <p className="text-xs text-accent mt-0.5">深层激活核心肌群，舒缓肩颈劳损，由内而外提升挺拔精气神。</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <div className="size-5 rounded-full bg-foreground/10 text-foreground flex items-center justify-center shrink-0 mt-0.5 text-xs font-bold">3</div>
                  <div>
                    <h4 className="text-sm font-semibold text-foreground">建立自信与生活仪式感</h4>
                    <p className="text-xs text-accent mt-0.5">见证每一次练习的进步，塑造优雅线条，展现充满生机的自我状态。</p>
                  </div>
                </li>
              </ul>
            </div>
          </div>

          {/* Part 2: Comfort & Fabric Quality */}
          <div className="card p-7 md:p-9 rounded-2xl flex flex-col justify-between gap-6 border border-accent/15">
            <div className="flex flex-col gap-5">
              <div className="flex items-center justify-between border-b border-accent/15 pb-3.5">
                <span className="text-xs font-semibold tracking-widest text-accent uppercase">Part 02</span>
                <span className="text-xs font-medium px-2.5 py-1 bg-accent/10 rounded-full text-foreground">EFFORTLESS COMFORT</span>
              </div>

              <div>
                <h3 className="text-2xl md:text-3xl font-bold text-foreground mb-2">
                  穿我们家的极致舒适
                </h3>
                <p className="text-sm text-accent leading-relaxed">
                  专为运动与日常打造的如第二层肌肤般的面料，零束缚触感，让舒适陪伴每一帧生活。
                </p>
              </div>

              <div className="relative h-60 md:h-64 rounded-xl overflow-hidden my-1">
                <img
                  src="https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786484971917-g68oe6g5.png"
                  alt="Clothing Comfort"
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent flex items-end p-4">
                  <p className="text-white text-xs md:text-sm font-medium">云感高弹面料，贴合身体无感无压</p>
                </div>
              </div>

              <ul className="space-y-3.5 pt-1">
                <li className="flex items-start gap-3">
                  <div className="size-5 rounded-full bg-foreground/10 text-foreground flex items-center justify-center shrink-0 mt-0.5 text-xs font-bold">1</div>
                  <div>
                    <h4 className="text-sm font-semibold text-foreground">云感无痕软包覆</h4>
                    <p className="text-xs text-accent mt-0.5">定制微纤维面料，触感轻盈幼滑，不挤肉不移位，享受无束缚自由。</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <div className="size-5 rounded-full bg-foreground/10 text-foreground flex items-center justify-center shrink-0 mt-0.5 text-xs font-bold">2</div>
                  <div>
                    <h4 className="text-sm font-semibold text-foreground">四向高弹与吸湿排汗</h4>
                    <p className="text-xs text-accent mt-0.5">随体动无阻伸展，微孔结构快速导湿，大汗淋漓依然保持干爽透气。</p>
                  </div>
                </li>
                <li className="flex items-start gap-3">
                  <div className="size-5 rounded-full bg-foreground/10 text-foreground flex items-center justify-center shrink-0 mt-0.5 text-xs font-bold">3</div>
                  <div>
                    <h4 className="text-sm font-semibold text-foreground">普拉提房到街头百搭</h4>
                    <p className="text-xs text-accent mt-0.5">高腰收腹修身裁剪，单穿或随手叠搭外套，轻松穿出高级无拘感。</p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default function EditorialSection() {
  return (
    <div data-webild-section="editorial" data-section="editorial" id="editorial">
      <EditorialInline />
    </div>
  );
}
