// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
        tag="ATHLEISURE BOUTIQUE"
        title="MOVE WELL. LOOK EFFORTLESS."
        description="From Pilates to urban everyday wear — where comfort meets effortless style."
        primaryButton={{
            text: "SHOP NEW ARRIVALS",
            href: "#new-arrivals"
          }}
        secondaryButton={{
            text: "OUR STORY",        href: "#about"}}
        items={[{"imageSrc":"https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786484971916-v4nwm7e8.png"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786484971917-g68oe6g5.png"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786484971918-jre4hmkb.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3HmmMlkqmPckqE8TM4WrSdIDbEH/uploaded-1786484971918-5iyx7jlj.png"}]}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
