// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "new-arrivals" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function NewArrivalsSection(): React.JSX.Element {
  return (
    <div id="new-arrivals" data-section="new-arrivals">
        <SectionErrorBoundary name="new-arrivals">
              <FeaturesRevealCardsBento
          tag="NEW COLLECTION"
          title="New Arrivals"
          description="最新都市运动服饰，兼顾机能与美学。"
          items={[
            { title: "Sculpt Leggings", description: "完美修身剪裁，透气面料。", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/sports-equipment-isolated-grey-surface_176420-11911.jpg" },
            { title: "Pilates Bodysuit", description: "极简线条，优雅运动感。", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/woman-sport-clothing-studio_23-2149374693.jpg" },
            { title: "Everyday Bra", description: "低支撑日常内衣。", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/high-angle-woman-lying-back_23-2148498692.jpg" },
            { title: "City Shorts", description: "都市轻运动版型。", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/warming-up_23-2148023742.jpg" },
            { title: "Seamless Top", description: "亲肤舒适面料。", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/fitness-sporty-girl-with-black-skin-afro-hairstyle-has-jogging-outdoor-wears-sportswear-smiles-looks-away-poses-white-wall-with-copy-space-your-sport-advertising-people-jogging_273609-29682.jpg" },
            { title: "Ribbed Set", description: "针织质感套装。", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/beautiful-model-with-perfect-tanned-body-female-putting-hood_158538-3534.jpg" },
            { title: "Active Jacket", description: "防风都市外套。", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-african-american-woman-wearing-coat-posing-street_181624-28798.jpg" }
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
