/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const items = [
  {
    title: "Sculpt Leggings",
    description: "完美修身剪裁，透气面料。",
    href: "#",
    imageSrc: "http://img.b2bpic.net/free-photo/sports-equipment-isolated-grey-surface_176420-11911.jpg"
  },
  {
    title: "Pilates Bodysuit",
    description: "极简线条，优雅运动感。",
    href: "#",
    imageSrc: "http://img.b2bpic.net/free-photo/woman-sport-clothing-studio_23-2149374693.jpg"
  },
  {
    title: "Everyday Bra",
    description: "低支撑日常内衣。",
    href: "#",
    imageSrc: "http://img.b2bpic.net/free-photo/high-angle-woman-lying-back_23-2148498692.jpg"
  },
  {
    title: "City Shorts",
    description: "都市轻运动版型。",
    href: "#",
    imageSrc: "http://img.b2bpic.net/free-photo/warming-up_23-2148023742.jpg"
  },
  {
    title: "Seamless Top",
    description: "亲肤舒适面料。",
    href: "#",
    imageSrc: "http://img.b2bpic.net/free-photo/fitness-sporty-girl-with-black-skin-afro-hairstyle-has-jogging-outdoor-wears-sportswear-smiles-looks-away-poses-white-wall-with-copy-space-your-sport-advertising-people-jogging_273609-29682.jpg"
  },
  {
    title: "Ribbed Set",
    description: "针织质感套装。",
    href: "#",
    imageSrc: "http://img.b2bpic.net/free-photo/beautiful-model-with-perfect-tanned-body-female-putting-hood_158538-3534.jpg"
  },
  {
    title: "Active Jacket",
    description: "防风都市外套。",
    href: "#",
    imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-african-american-woman-wearing-coat-posing-street_181624-28798.jpg"
  }
];

type FeatureItem = {
  title: string;
  description: string;
  href: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesRevealCardsBentoProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: [FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const NewArrivalsInline = () => {
  const gridClasses = [
    "md:col-span-2",
    "md:col-span-4",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-2",
    "md:col-span-2",
    "md:col-span-2",
  ];

  const staggerDelays = [
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
    0.2,
  ];

  return (
    <section aria-label="Features reveal cards bento section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"NEW COLLECTION"}</p>
          </div>

          <TextAnimation
            text={"New Arrivals"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"最新都市运动服饰，兼顾机能与美学。"}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            <Button text="SHOP NOW" href="#complete-look" variant="primary" />
          </div>
        </div>

        <div className="w-content-width mx-auto grid grid-cols-1 md:grid-cols-6 gap-3">
          {items.map((item, index) => (
            <ScrollReveal key={item.title} variant="slide-up" delay={staggerDelays[index]} className={cls("col-span-1 group", gridClasses[index])}>
              <a href={item.href} className="block relative overflow-hidden rounded">
                <div className="h-80 xl:h-100 2xl:h-120 overflow-hidden">
                  <ImageOrVideo
                    imageSrc={item.imageSrc}
                    videoSrc={item.videoSrc}
                    className="rounded group-hover:scale-105 transition-transform duration-500"
                  />
                </div>
                <div className="absolute -inset-x-px -bottom-px h-2/5 backdrop-blur-xl mask-fade-top-overlay" aria-hidden="true" />
                <div className="absolute inset-x-3 bottom-3 2xl:inset-x-4 2xl:bottom-4 z-10">
                  <div className="relative flex flex-col gap-1 md:gap-0 md:group-hover:gap-1 p-3 2xl:p-4 transition-all duration-400">
                    <div className="absolute inset-0 -z-10 card rounded translate-y-0 opacity-100 md:translate-y-full md:opacity-0 transition-all duration-400 ease-out md:group-hover:translate-y-0 md:group-hover:opacity-100" />
                    <h3 className="text-2xl font-semibold leading-snug text-foreground md:text-white transition-colors duration-400 md:group-hover:text-foreground">
                      {item.title}
                    </h3>
                    <div className="grid grid-rows-[1fr] md:grid-rows-[0fr] transition-all duration-400 ease-out md:group-hover:grid-rows-[1fr]">
                      <p className="overflow-hidden text-base leading-snug text-foreground opacity-100 md:opacity-0 transition-opacity duration-400 md:group-hover:opacity-100">
                        {item.description}
                      </p>
                    </div>
                  </div>
                </div>
              </a>
            </ScrollReveal>
          ))}
        </div>
      </div>
    </section>
  );
};

export default function NewArrivalsSection() {
  return (
    <div data-webild-section="new-arrivals" data-section="new-arrivals" id="new-arrivals">
      <NewArrivalsInline />
    </div>
  );
}
